/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ListenHubPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  apiKey: "",
  mode: "podcast",
  podcastSubMode: "debate",
  flowSpeechSubMode: "smart",
  language: "zh",
  speaker1: "CN-Man-Beijing-V2",
  speaker2: "chat-girl-105-cn"
};
var BUILTIN_SPEAKERS = {
  zh: [
    { id: "chat-girl-105-cn", name: "\u6653\u66FC", language: "zh", gender: "female", audioPreviewUrl: "https://assets.listenhub.ai/listenhub-public-prod/audios/chat-girl-105-cn_pending_1761140378494.mp3" },
    { id: "suzhe-45bbbe54", name: "\u82CF\u54F2", language: "zh", gender: "male", audioPreviewUrl: "https://assets.listenhub.ai/listenhub-public-prod/audios/suzhe-45bbbe54_pending_1761140378388.mp3" },
    { id: "gaoqing3-bfb5c88a", name: "\u9AD8\u6674", language: "zh", gender: "female", audioPreviewUrl: "https://assets.listenhub.ai/listenhub-public-prod/audios/gaoqing3-bfb5c88a_pending_1761140378495.mp3" },
    { id: "CN-Man-Beijing-V2", name: "\u539F\u91CE", language: "zh", gender: "male", audioPreviewUrl: "https://assets.listenhub.ai/listenhub-public-prod/audios/CN-Man-Beijing-V2_pending_1761140378252.mp3" },
    { id: "liyan2-ef9401ec", name: "\u56FD\u680B", language: "zh", gender: "male", audioPreviewUrl: "https://assets.listenhub.ai/listenhub-public-prod/audios/liyan2-ef9401ec_pending_1761140378388.mp3" },
    { id: "liyan3-f74976d9", name: "\u5B50\u58A8", language: "zh", gender: "male", audioPreviewUrl: "https://assets.listenhub.ai/listenhub-public-prod/audios/liyan3-f74976d9_pending_1761140378112.mp3" },
    { id: "zhibonusheng-7b0dbae2", name: "\u76F4\u64AD\u96EA\u59D0", language: "zh", gender: "female", audioPreviewUrl: "https://assets.listenhub.ai/listenhub-public-prod/audios/zhibonusheng-7b0dbae2_pending_1761204468716.mp3" },
    { id: "shuoshurennan-fdfa85f9", name: "\u5E38\u56DB\u7237", language: "zh", gender: "male", audioPreviewUrl: "https://assets.listenhub.ai/listenhub-public-prod/audios/shuoshurennan-fdfa85f9_pending_1761140378113.mp3" },
    { id: "pingshu-c7c18f5a", name: "\u53E4\u4ECA\u5148\u751F", language: "zh", gender: "male", audioPreviewUrl: "https://assets.listenhub.ai/listenhub-public-prod/audios/pingshu-c7c18f5a_pending_1761140378252.mp3" },
    { id: "midnightaxing-0bf9d7a5", name: "\u51A5\u60F3\u963F\u661F", language: "zh", gender: "male", audioPreviewUrl: "https://assets.listenhub.ai/listenhub-public-prod/audios/midnightaxing-0bf9d7a5_pending_1761140378712.mp3" },
    { id: "midnightalan-cb312cb6", name: "\u51A5\u60F3\u963F\u5C9A", language: "zh", gender: "female", audioPreviewUrl: "https://assets.listenhub.ai/listenhub-public-prod/audios/midnightalan-cb312cb6_pending_1761140378713.mp3" },
    { id: "zhibonansheng-80bf8621", name: "\u76F4\u64AD\u6D69\u54E5", language: "zh", gender: "male", audioPreviewUrl: "https://assets.listenhub.ai/listenhub-public-prod/audios/zhibonansheng-80bf8621_pending_1761140378253.mp3" },
    { id: "huibennulaoshi-bf2bbe1f", name: "\u6545\u4E8B\u4E91\u8212", language: "zh", gender: "female", audioPreviewUrl: "https://assets.listenhub.ai/listenhub-public-prod/audios/huibennulaoshi-bf2bbe1f_pending_1761140377976.mp3" },
    { id: "gushijingling-720c0ae5", name: "\u6545\u4E8B\u7CBE\u7075", language: "zh", gender: "male", audioPreviewUrl: "https://assets.listenhub.ai/listenhub-public-prod/audios/gushijingling-720c0ae5_pending_1761205947072.mp3" },
    { id: "dp-6cc9831f", name: "\u7EA6\u7FF0\u5927\u53D4", language: "zh", gender: "male", audioPreviewUrl: "https://assets.listenhub.ai/listenhub-public-prod/audios/dp-6cc9831f_demo_audio.mp3" },
    { id: "sam-34cf3074", name: "\u5C71\u59C6\u5927\u53D4", language: "zh", gender: "male", audioPreviewUrl: "https://assets.listenhub.ai/listenhub-public-prod/audios/sam-34cf3074_demo_audio.mp3" },
    { id: "bajie-4f6ab1a8", name: "\u516B\u6212", language: "zh", gender: "male", audioPreviewUrl: "https://assets.listenhub.ai/listenhub-public-prod/audios/bajie-4f6ab1a8_pending_1761140377975.mp3" },
    { id: "houge-ce107859", name: "\u7334\u54E5", language: "zh", gender: "male", audioPreviewUrl: "https://assets.listenhub.ai/listenhub-public-prod/audios/houge-ce107859_pending_1761140377976.mp3" },
    { id: "xinyi6", name: "\u8BD7\u6DB5", language: "zh", gender: "female", audioPreviewUrl: "https://assets.listenhub.ai/listenhub-public-prod/audios/xinyi6_pending_1761140378113.mp3" },
    { id: "nanzhongyin-4897116a", name: "\u632F\u677E", language: "zh", gender: "male", audioPreviewUrl: "https://assets.listenhub.ai/listenhub-public-prod/audios/nanzhongyin-4897116a_pending_1761140378495.mp3" },
    { id: "xiaoyun", name: "\u82E5\u4E91", language: "zh", gender: "female", audioPreviewUrl: "https://assets.listenhub.ai/listenhub-public-prod/audios/xiaoyun_pending_1761140378113.mp3" },
    { id: "nvdiyin-7b293152", name: "\u66AE\u6B4C", language: "zh", gender: "female", audioPreviewUrl: "https://assets.listenhub.ai/listenhub-public-prod/audios/nvdiyin-7b293152_pending_1761140378253.mp3" },
    { id: "shuoshurennan-b09f844f", name: "\u67F3\u98DE\u971C", language: "zh", gender: "female", audioPreviewUrl: "https://assets.listenhub.ai/listenhub-public-prod/audios/shuoshurennan-b09f844f_pending_1761140378253.mp3" },
    { id: "ASMR-Male-CN", name: "\u8FDC\u821F (ASMR)", language: "zh", gender: "male", audioPreviewUrl: "https://assets.listenhub.ai/listenhub-public-prod/audios/ASMR-Male-CN_pending_1761140378494.mp3" },
    { id: "ASMR-Female-CN", name: "\u5B9B\u661F (ASMR)", language: "zh", gender: "female", audioPreviewUrl: "https://assets.listenhub.ai/listenhub-public-prod/audios/ASMR-Female-CN_pending_1761140378494.mp3" },
    { id: "1luoxiaohei1vocals-88bfc421", name: "\u5C0F\u82B1\u5996", language: "zh", gender: "female", audioPreviewUrl: "https://assets.listenhub.ai/listenhub-public-prod/audios/1luoxiaohei1vocals-88bfc421_demo_audio.mp3" },
    { id: "hajimi-427f918d", name: "\u54C8\u57FA\u7C73", language: "zh", gender: "female", audioPreviewUrl: "https://assets.listenhub.ai/listenhub-public-prod/audios/hajimi-427f918d_demo_audio.mp3" }
  ],
  en: [
    { id: "EN-US-News-Male", name: "News Anchor (Male)", language: "en", gender: "male", audioPreviewUrl: "" },
    { id: "EN-US-News-Female", name: "News Anchor (Female)", language: "en", gender: "female", audioPreviewUrl: "" },
    { id: "EN-US-Casual-Male", name: "Casual (Male)", language: "en", gender: "male", audioPreviewUrl: "" },
    { id: "EN-US-Casual-Female", name: "Casual (Female)", language: "en", gender: "female", audioPreviewUrl: "" }
  ]
};
var ListenHubPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "generate-audio",
      name: "\u751F\u6210\u97F3\u9891\u5185\u5BB9",
      checkCallback: (checking) => {
        const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
        if (view) {
          if (!checking) {
            this.generateAudio(view.editor, view);
          }
          return true;
        }
        return false;
      }
    });
    this.addSettingTab(new ListenHubSettingTab(this.app, this));
    this.addRibbonIcon("audio-lines", "ListenHub: \u751F\u6210\u97F3\u9891", () => {
      const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
      if (view) {
        this.generateAudio(view.editor, view);
      } else {
        new import_obsidian.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A\u6587\u6863");
      }
    });
  }
  onunload() {
    console.log("Unloading ListenHub plugin");
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async generateAudio(editor, view) {
    var _a, _b;
    if (!this.settings.apiKey) {
      new import_obsidian.Notice("\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u914D\u7F6E API Key");
      return;
    }
    let content = editor.getValue();
    if (!content || content.trim().length === 0) {
      new import_obsidian.Notice("\u5F53\u524D\u6587\u6863\u5185\u5BB9\u4E3A\u7A7A");
      return;
    }
    let docTitle = ((_a = view.file) == null ? void 0 : _a.name) || "\u672A\u547D\u540D\u6587\u6863";
    if (view.file) {
      const cache = this.app.metadataCache.getFileCache(view.file);
      if ((_b = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _b.title) {
        docTitle = cache.frontmatter.title;
      }
    }
    content = this.extractContentFromMarkdown(content);
    if (!content || content.trim().length === 0) {
      new import_obsidian.Notice("\u672A\u627E\u5230\u6709\u6548\u5185\u5BB9\uFF08\u9700\u8981\u81F3\u5C11\u4E00\u4E2A ### \u4E09\u7EA7\u6807\u9898\uFF09");
      return;
    }
    new GenerateAudioModal(this.app, this, content, docTitle, view).open();
  }
  /**
   * 提取 Markdown 内容：
   * 1. 移除 YAML frontmatter
   * 2. 从第一个 ### 三级标题开始提取内容
   * 3. 移除 <svg> 标签及其内容
   * 4. 移除 Markdown 图片语法
   */
  extractContentFromMarkdown(content) {
    content = content.replace(/^---\s*\n[\s\S]*?\n---\s*\n/m, "");
    const h3Match = content.match(/^###\s+.+$/m);
    let processedContent = content;
    if (h3Match && h3Match.index !== void 0) {
      processedContent = content.substring(h3Match.index);
    } else {
      console.warn("\u672A\u627E\u5230 ### \u4E09\u7EA7\u6807\u9898\uFF0C\u5C06\u4F7F\u7528\u5B8C\u6574\u5185\u5BB9\uFF08\u5DF2\u79FB\u9664 YAML\uFF09");
    }
    processedContent = processedContent.replace(/<svg[\s\S]*?<\/svg>/gi, "");
    processedContent = processedContent.replace(/!\[([^\]]*)\]\(([^)]+)\)/g, "");
    processedContent = processedContent.replace(/!\[\[([^\]]+)\]\]/g, "");
    return processedContent.trim();
  }
  async callListenHubAPI(content, title) {
    const baseUrl = "https://api.marswave.ai";
    let endpoint = "";
    let mode = "";
    if (this.settings.mode === "podcast") {
      endpoint = `${baseUrl}/openapi/v1/podcast/episodes`;
      mode = this.settings.podcastSubMode;
    } else {
      endpoint = `${baseUrl}/openapi/v1/flow-speech/episodes`;
      mode = this.settings.flowSpeechSubMode;
    }
    const requestBody = {
      mode,
      language: this.settings.language
    };
    if (this.settings.mode === "podcast") {
      const queryText = title ? `${title}

${content}` : content;
      requestBody.query = queryText;
    } else {
      const textContent = title ? `${title}

${content}` : content;
      requestBody.sources = [
        {
          type: "text",
          content: textContent
        }
      ];
    }
    const speakers = [];
    if (this.settings.speaker1) {
      speakers.push({ speakerId: this.settings.speaker1 });
    }
    if (this.settings.mode === "podcast" && this.settings.speaker2) {
      speakers.push({ speakerId: this.settings.speaker2 });
    }
    if (speakers.length > 0) {
      requestBody.speakers = speakers;
    }
    console.log("ListenHub API \u8BF7\u6C42:");
    console.log("- Endpoint:", endpoint);
    console.log("- Request Body:", JSON.stringify(requestBody, null, 2));
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url: endpoint,
        method: "POST",
        headers: {
          "Authorization": `Bearer ${this.settings.apiKey}`,
          "Content-Type": "application/json"
        },
        body: JSON.stringify(requestBody),
        throw: false
      });
      console.log("ListenHub API \u54CD\u5E94:");
      console.log("- Status:", response.status);
      console.log("- Headers:", response.headers);
      console.log("- Body:", response.text);
      if (response.status === 200 || response.status === 201) {
        return response.json;
      } else {
        const errorMsg = `API \u8BF7\u6C42\u5931\u8D25 (${response.status}): ${response.text}`;
        console.error("ListenHub API \u9519\u8BEF:", errorMsg);
        return {
          success: false,
          error: errorMsg,
          message: response.text
        };
      }
    } catch (error) {
      console.error("ListenHub API \u5F02\u5E38:", error);
      return {
        success: false,
        error: "\u7F51\u7EDC\u8BF7\u6C42\u5931\u8D25",
        message: error.message
      };
    }
  }
  async testAPIConnection() {
    if (!this.settings.apiKey) {
      return { success: false, message: "\u8BF7\u5148\u8F93\u5165 API Key" };
    }
    const testContent = "\u8FD9\u662F\u4E00\u4E2A\u6D4B\u8BD5\u5185\u5BB9\uFF0C\u7528\u4E8E\u9A8C\u8BC1 API \u8FDE\u63A5\u3002";
    const testTitle = "API \u8FDE\u63A5\u6D4B\u8BD5";
    try {
      const result = await this.callListenHubAPI(testContent, testTitle);
      if (result.success !== false && result.data) {
        return {
          success: true,
          message: `\u8FDE\u63A5\u6210\u529F\uFF01Episode ID: ${result.data.episode_id}`
        };
      } else {
        return {
          success: false,
          message: result.error || result.message || "\u8FDE\u63A5\u5931\u8D25"
        };
      }
    } catch (error) {
      return {
        success: false,
        message: `\u8FDE\u63A5\u5931\u8D25: ${error.message}`
      };
    }
  }
  /**
   * 获取可用音色列表（使用内置数据）
   */
  async getSpeakers(language = "zh") {
    const lang = language === "en" ? "en" : "zh";
    const speakers = BUILTIN_SPEAKERS[lang];
    if (speakers && speakers.length > 0) {
      return { success: true, speakers };
    }
    return { success: false, message: "\u6682\u65E0\u53EF\u7528\u97F3\u8272" };
  }
  /**
   * 更新文档：添加 listenhub 属性和 iframe 播放器
   */
  async updateDocumentWithEpisode(file, episodeId) {
    try {
      const content = await this.app.vault.read(file);
      const updatedContent = this.addListenHubToDocument(content, episodeId);
      await this.app.vault.modify(file, updatedContent);
      new import_obsidian.Notice("\u2705 \u6587\u6863\u5DF2\u66F4\u65B0\uFF1A\u6DFB\u52A0\u4E86 ListenHub \u5C5E\u6027\u548C\u64AD\u653E\u5668");
    } catch (error) {
      console.error("\u66F4\u65B0\u6587\u6863\u5931\u8D25:", error);
      new import_obsidian.Notice(`\u274C \u66F4\u65B0\u6587\u6863\u5931\u8D25: ${error.message}`);
    }
  }
  /**
   * 在文档中添加 listenhub 属性和 iframe
   */
  addListenHubToDocument(content, episodeId) {
    const listenHubUrl = `https://listenhub.ai/zh/episode/${episodeId}`;
    const iframeCode = `<iframe src="https://listenhub.ai/embed/episode/${episodeId}" style="border-radius: 12px" width="100%" height="154px" frameborder="0" allowfullscreen></iframe>

`;
    const yamlRegex = /^---\s*\n([\s\S]*?)\n---\s*\n/;
    const yamlMatch = content.match(yamlRegex);
    if (yamlMatch) {
      const yamlContent = yamlMatch[1];
      const afterYaml = content.substring(yamlMatch[0].length);
      let updatedYaml = yamlContent;
      if (/^listenhub:\s*.+$/m.test(yamlContent)) {
        updatedYaml = yamlContent.replace(/^listenhub:\s*.+$/m, `listenhub: ${listenHubUrl}`);
      } else {
        updatedYaml = yamlContent + `
listenhub: ${listenHubUrl}`;
      }
      const iframeRegex = /<iframe src="https:\/\/listenhub\.ai\/embed\/episode\/[^"]+"/;
      let updatedAfterYaml = afterYaml;
      if (iframeRegex.test(afterYaml)) {
        updatedAfterYaml = afterYaml.replace(
          /<iframe src="https:\/\/listenhub\.ai\/embed\/episode\/[^"]+"\s+style="[^"]*"\s+width="[^"]*"\s+height="[^"]*"\s+frameborder="[^"]*"\s+allowfullscreen><\/iframe>\s*\n*/,
          iframeCode
        );
      } else {
        updatedAfterYaml = iframeCode + afterYaml.trimStart();
      }
      return `---
${updatedYaml}
---
${updatedAfterYaml}`;
    } else {
      const newYaml = `---
listenhub: ${listenHubUrl}
---
`;
      const iframeRegex = /<iframe src="https:\/\/listenhub\.ai\/embed\/episode\/[^"]+"/;
      let updatedContent = content;
      if (iframeRegex.test(content)) {
        updatedContent = content.replace(
          /<iframe src="https:\/\/listenhub\.ai\/embed\/episode\/[^"]+"\s+style="[^"]*"\s+width="[^"]*"\s+height="[^"]*"\s+frameborder="[^"]*"\s+allowfullscreen><\/iframe>\s*\n*/,
          iframeCode
        );
      } else {
        updatedContent = iframeCode + content.trimStart();
      }
      return newYaml + updatedContent;
    }
  }
};
var GenerateAudioModal = class extends import_obsidian.Modal {
  constructor(app, plugin, content, fileName, view) {
    super(app);
    this.plugin = plugin;
    this.content = content;
    this.fileName = fileName;
    this.view = view;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\u751F\u6210\u97F3\u9891\u5185\u5BB9" });
    const infoDiv = contentEl.createDiv({ cls: "listenhub-modal-info" });
    infoDiv.createEl("p", {
      text: `\u6587\u6863: ${this.fileName}`
    });
    const modeText = this.plugin.settings.mode === "podcast" ? "Podcast" : "FlowSpeech";
    const subModeText = this.plugin.settings.mode === "podcast" ? this.plugin.settings.podcastSubMode : this.plugin.settings.flowSpeechSubMode;
    infoDiv.createEl("p", {
      text: `\u6A21\u5F0F: ${modeText} - ${subModeText}`
    });
    infoDiv.createEl("p", {
      text: `\u5185\u5BB9\u957F\u5EA6: ${this.content.length} \u5B57\u7B26`
    });
    const modeDescriptions = {
      "deep": "\u6DF1\u5EA6\u5206\u6790\uFF0C\u5185\u5BB9\u8D28\u91CF\u9AD8 (2-4\u5206\u949F)",
      "quick": "\u5FEB\u901F\u751F\u6210\uFF0C\u6548\u7387\u4F18\u5148 (1-2\u5206\u949F)",
      "debate": "\u53CC\u4E3B\u6301\u4EBA\u8FA9\u8BBA\u5F62\u5F0F (2-4\u5206\u949F)",
      "smart": "AI\u667A\u80FD\u4F18\u5316\u5185\u5BB9 (1-2\u5206\u949F)",
      "direct": "\u6587\u672C\u76F4\u63A5\u8F6C\u6362\u8BED\u97F3 (1-2\u5206\u949F)"
    };
    const currentMode = this.plugin.settings.mode === "podcast" ? this.plugin.settings.podcastSubMode : this.plugin.settings.flowSpeechSubMode;
    infoDiv.createEl("p", {
      text: `\u8BF4\u660E: ${modeDescriptions[currentMode]}`,
      cls: "listenhub-mode-description"
    });
    const buttonDiv = contentEl.createDiv({ cls: "listenhub-modal-buttons" });
    const generateBtn = buttonDiv.createEl("button", {
      text: "\u5F00\u59CB\u751F\u6210",
      cls: "mod-cta"
    });
    generateBtn.addEventListener("click", async () => {
      var _a;
      generateBtn.disabled = true;
      generateBtn.setText("\u751F\u6210\u4E2D...");
      const result = await this.plugin.callListenHubAPI(this.content, this.fileName);
      console.log("\u{1F50D} \u5B8C\u6574\u7684 API \u54CD\u5E94\u7ED3\u679C:", result);
      console.log("\u{1F50D} result.data:", result.data);
      console.log("\u{1F50D} result.data?.episode_id:", (_a = result.data) == null ? void 0 : _a.episode_id);
      if (result.success !== false && result.data) {
        const episodeId = result.data.episode_id || result.data.episodeId || result.data.id;
        console.log("\u2705 \u63D0\u53D6\u7684 Episode ID:", episodeId);
        if (!episodeId) {
          console.error("\u274C \u65E0\u6CD5\u4ECE\u54CD\u5E94\u4E2D\u83B7\u53D6 Episode ID\uFF0C\u5B8C\u6574\u54CD\u5E94:", JSON.stringify(result, null, 2));
          new import_obsidian.Notice("\u274C \u751F\u6210\u5931\u8D25: \u65E0\u6CD5\u83B7\u53D6 Episode ID");
          this.close();
          return;
        }
        if (this.view && this.view.file) {
          await this.plugin.updateDocumentWithEpisode(this.view.file, episodeId);
        }
        new ResultModal(this.app, result.data, episodeId).open();
      } else {
        new import_obsidian.Notice(`\u274C \u751F\u6210\u5931\u8D25: ${result.error || result.message || "\u672A\u77E5\u9519\u8BEF"}`);
      }
      this.close();
    });
    const cancelBtn = buttonDiv.createEl("button", { text: "\u53D6\u6D88" });
    cancelBtn.addEventListener("click", () => {
      this.close();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var ResultModal = class extends import_obsidian.Modal {
  constructor(app, data, episodeId) {
    super(app);
    this.data = data;
    this.episodeId = episodeId;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\u751F\u6210\u7ED3\u679C" });
    const resultDiv = contentEl.createDiv({ cls: "listenhub-result" });
    resultDiv.createEl("p", {
      text: `Episode ID: ${this.episodeId || "\u751F\u6210\u4E2D..."}`
    });
    resultDiv.createEl("p", {
      text: `\u72B6\u6001: ${this.data.status || "\u5904\u7406\u4E2D"}`
    });
    if (this.data.audio_url) {
      const audioLink = resultDiv.createEl("a", {
        text: "\u{1F3A7} \u64AD\u653E\u97F3\u9891",
        href: this.data.audio_url
      });
      audioLink.setAttr("target", "_blank");
    } else {
      resultDiv.createEl("p", {
        text: "\u97F3\u9891\u6B63\u5728\u5904\u7406\u4E2D\uFF0C\u8BF7\u7A0D\u540E\u5728 ListenHub \u5E73\u53F0\u67E5\u770B",
        cls: "listenhub-processing"
      });
    }
    if (this.data.message) {
      resultDiv.createEl("p", {
        text: `\u6D88\u606F: ${this.data.message}`,
        cls: "listenhub-message"
      });
    }
    const linkDiv = contentEl.createDiv({ cls: "listenhub-link-section" });
    linkDiv.style.marginTop = "16px";
    linkDiv.style.marginBottom = "16px";
    const episodeUrl = `https://listenhub.ai/zh/episode/${this.episodeId}`;
    const listenHubLink = linkDiv.createEl("a", {
      text: "\u{1F4DA} \u5728 ListenHub \u67E5\u770B\u8BE6\u60C5",
      href: episodeUrl
    });
    listenHubLink.setAttr("target", "_blank");
    listenHubLink.style.display = "block";
    listenHubLink.style.textAlign = "center";
    listenHubLink.style.padding = "8px";
    listenHubLink.style.textDecoration = "none";
    listenHubLink.style.color = "var(--interactive-accent)";
    const buttonDiv = contentEl.createDiv({ cls: "listenhub-button-group" });
    buttonDiv.style.marginTop = "16px";
    const closeBtn = buttonDiv.createEl("button", {
      text: "\u5173\u95ED",
      cls: "mod-cta"
    });
    closeBtn.addEventListener("click", () => {
      this.close();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var ListenHubSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.speakerListContainer = null;
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "ListenHub \u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("API Key").setDesc("\u8F93\u5165\u4F60\u7684 ListenHub API Key").addText((text) => text.setPlaceholder("\u8BF7\u8F93\u5165 API Key").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
      this.plugin.settings.apiKey = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u6D4B\u8BD5\u8FDE\u63A5").setDesc("\u6D4B\u8BD5 API Key \u662F\u5426\u6709\u6548").addButton((button) => button.setButtonText("\u6D4B\u8BD5\u8FDE\u63A5").setCta().onClick(async () => {
      button.setButtonText("\u6D4B\u8BD5\u4E2D...");
      button.setDisabled(true);
      const result = await this.plugin.testAPIConnection();
      if (result.success) {
        new import_obsidian.Notice(`\u2705 ${result.message}`);
      } else {
        new import_obsidian.Notice(`\u274C ${result.message}`);
      }
      button.setButtonText("\u6D4B\u8BD5\u8FDE\u63A5");
      button.setDisabled(false);
    }));
    containerEl.createEl("h3", { text: "\u751F\u6210\u6A21\u5F0F" });
    new import_obsidian.Setting(containerEl).setName("\u4E3B\u6A21\u5F0F").setDesc("\u9009\u62E9\u751F\u6210\u7C7B\u578B").addDropdown((dropdown) => dropdown.addOption("podcast", "Podcast (\u64AD\u5BA2)").addOption("flow-speech", "FlowSpeech (\u6D41\u5F0F\u8BED\u97F3)").setValue(this.plugin.settings.mode).onChange(async (value) => {
      this.plugin.settings.mode = value;
      await this.plugin.saveSettings();
      this.display();
    }));
    if (this.plugin.settings.mode === "podcast") {
      new import_obsidian.Setting(containerEl).setName("Podcast \u5B50\u6A21\u5F0F").setDesc("\u9009\u62E9\u64AD\u5BA2\u751F\u6210\u6A21\u5F0F").addDropdown((dropdown) => dropdown.addOption("deep", "Deep - \u6DF1\u5EA6\u5206\u6790").addOption("quick", "Quick - \u5FEB\u901F\u751F\u6210").addOption("debate", "Debate - \u8FA9\u8BBA\u5F62\u5F0F").setValue(this.plugin.settings.podcastSubMode).onChange(async (value) => {
        this.plugin.settings.podcastSubMode = value;
        await this.plugin.saveSettings();
      }));
      const descDiv = containerEl.createDiv({ cls: "listenhub-mode-descriptions" });
      descDiv.createEl("p", { text: "\u2022 Deep: \u6DF1\u5EA6\u5206\u6790\uFF0C\u5185\u5BB9\u8D28\u91CF\u9AD8\uFF0C\u9002\u5408\u4E13\u4E1A\u77E5\u8BC6\u5206\u4EAB (2-4\u5206\u949F)" });
      descDiv.createEl("p", { text: "\u2022 Quick: \u5FEB\u901F\u751F\u6210\uFF0C\u6548\u7387\u4F18\u5148\uFF0C\u9002\u5408\u65B0\u95FB\u5FEB\u62A5 (1-2\u5206\u949F)" });
      descDiv.createEl("p", { text: "\u2022 Debate: \u53CC\u4E3B\u6301\u4EBA\u8FA9\u8BBA\u5F62\u5F0F\uFF0C\u9002\u5408\u89C2\u70B9\u8BA8\u8BBA (2-4\u5206\u949F)" });
    }
    if (this.plugin.settings.mode === "flow-speech") {
      new import_obsidian.Setting(containerEl).setName("FlowSpeech \u5B50\u6A21\u5F0F").setDesc("\u9009\u62E9\u6D41\u5F0F\u8BED\u97F3\u751F\u6210\u6A21\u5F0F").addDropdown((dropdown) => dropdown.addOption("smart", "Smart - \u667A\u80FD\u4F18\u5316").addOption("direct", "Direct - \u76F4\u63A5\u8F6C\u6362").setValue(this.plugin.settings.flowSpeechSubMode).onChange(async (value) => {
        this.plugin.settings.flowSpeechSubMode = value;
        await this.plugin.saveSettings();
      }));
      const descDiv = containerEl.createDiv({ cls: "listenhub-mode-descriptions" });
      descDiv.createEl("p", { text: "\u2022 Smart: AI\u667A\u80FD\u4F18\u5316\u5185\u5BB9\uFF0C\u4FEE\u590D\u8BED\u53E5\u4E0D\u901A\u987A\u3001\u9519\u522B\u5B57 (1-2\u5206\u949F\uFF0C\u5355\u97F3\u8272)" });
      descDiv.createEl("p", { text: "\u2022 Direct: \u6587\u672C\u76F4\u63A5\u8F6C\u6362\u8BED\u97F3\uFF0C\u7C7B\u4F3CTTS (1-2\u5206\u949F\uFF0C\u5355\u97F3\u8272)" });
    }
    containerEl.createEl("h3", { text: "\u8BED\u8A00\u548C\u97F3\u8272\u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u8BED\u8A00").setDesc("\u9009\u62E9\u751F\u6210\u5185\u5BB9\u7684\u8BED\u8A00").addDropdown((dropdown) => dropdown.addOption("zh", "\u4E2D\u6587 (Chinese)").addOption("en", "\u82F1\u6587 (English)").setValue(this.plugin.settings.language).onChange(async (value) => {
      this.plugin.settings.language = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u97F3\u8272 1 (Speaker 1)").setDesc("\u7B2C\u4E00\u4E2A\u8BF4\u8BDD\u4EBA\u7684\u97F3\u8272ID").addText((text) => text.setPlaceholder("\u4F8B\u5982: CN-Man-Beijing-V2").setValue(this.plugin.settings.speaker1).onChange(async (value) => {
      this.plugin.settings.speaker1 = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("\u97F3\u8272 2 (Speaker 2)").setDesc("\u7B2C\u4E8C\u4E2A\u8BF4\u8BDD\u4EBA\u7684\u97F3\u8272ID\uFF08\u6CE8\u610F\uFF1A\u4EC5 Podcast \u6A21\u5F0F\u652F\u6301\u53CC\u97F3\u8272\uFF0CFlowSpeech \u6A21\u5F0F\u53EA\u4F7F\u7528\u7B2C\u4E00\u4E2A\u97F3\u8272\uFF09").addText((text) => text.setPlaceholder("\u4F8B\u5982: chat-girl-105-cn").setValue(this.plugin.settings.speaker2).onChange(async (value) => {
      this.plugin.settings.speaker2 = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "\u53EF\u7528\u97F3\u8272\u5217\u8868" });
    new import_obsidian.Setting(containerEl).setName("\u52A0\u8F7D\u97F3\u8272").setDesc("\u4ECE ListenHub API \u83B7\u53D6\u53EF\u7528\u97F3\u8272\u5217\u8868").addDropdown((dropdown) => dropdown.addOption("zh", "\u4E2D\u6587").addOption("en", "\u82F1\u6587").setValue(this.plugin.settings.language)).addButton((button) => button.setButtonText("\u52A0\u8F7D\u97F3\u8272\u5217\u8868").setCta().onClick(async () => {
      const langDropdown = containerEl.querySelector(".setting-item:has(button) select");
      const lang = (langDropdown == null ? void 0 : langDropdown.value) || this.plugin.settings.language;
      button.setButtonText("\u52A0\u8F7D\u4E2D...");
      button.setDisabled(true);
      const result = await this.plugin.getSpeakers(lang);
      if (result.success && result.speakers) {
        this.renderSpeakerList(result.speakers);
        new import_obsidian.Notice(`\u2705 \u5DF2\u52A0\u8F7D ${result.speakers.length} \u4E2A\u97F3\u8272`);
      } else {
        new import_obsidian.Notice(`\u274C ${result.message || "\u52A0\u8F7D\u5931\u8D25"}`);
      }
      button.setButtonText("\u52A0\u8F7D\u97F3\u8272\u5217\u8868");
      button.setDisabled(false);
    }));
    this.speakerListContainer = containerEl.createDiv({ cls: "listenhub-speaker-list-container" });
    containerEl.createEl("h3", { text: "\u4F7F\u7528\u8BF4\u660E" });
    const usageDiv = containerEl.createDiv({ cls: "listenhub-usage" });
    usageDiv.createEl("p", { text: "1. \u5728\u8BBE\u7F6E\u4E2D\u914D\u7F6E API Key \u5E76\u6D4B\u8BD5\u8FDE\u63A5" });
    usageDiv.createEl("p", { text: "2. \u9009\u62E9\u751F\u6210\u6A21\u5F0F\u548C\u5B50\u6A21\u5F0F" });
    usageDiv.createEl("p", { text: "3. \u6253\u5F00\u8981\u8F6C\u6362\u7684\u6587\u6863" });
    usageDiv.createEl("p", { text: "4. \u70B9\u51FB\u5DE6\u4FA7\u529F\u80FD\u533A\u7684\u97F3\u9891\u56FE\u6807\u6216\u4F7F\u7528\u547D\u4EE4\u9762\u677F" });
    usageDiv.createEl("p", { text: "5. \u7B49\u5F85\u751F\u6210\u5B8C\u6210\uFF0C\u67E5\u770B\u7ED3\u679C" });
  }
  /**
   * 渲染音色列表
   */
  renderSpeakerList(speakers) {
    if (!this.speakerListContainer)
      return;
    this.speakerListContainer.empty();
    if (speakers.length === 0) {
      this.speakerListContainer.createEl("p", { text: "\u6682\u65E0\u53EF\u7528\u97F3\u8272", cls: "listenhub-no-speakers" });
      return;
    }
    const table = this.speakerListContainer.createEl("table", { cls: "listenhub-speaker-table" });
    const thead = table.createEl("thead");
    const headerRow = thead.createEl("tr");
    headerRow.createEl("th", { text: "\u97F3\u8272\u540D\u79F0" });
    headerRow.createEl("th", { text: "ID" });
    headerRow.createEl("th", { text: "\u6027\u522B" });
    headerRow.createEl("th", { text: "\u8BD5\u542C" });
    headerRow.createEl("th", { text: "\u64CD\u4F5C" });
    const tbody = table.createEl("tbody");
    for (const speaker of speakers) {
      const row = tbody.createEl("tr");
      row.createEl("td", { text: speaker.name });
      const idCell = row.createEl("td");
      const idCode = idCell.createEl("code", { text: speaker.id, cls: "listenhub-speaker-id" });
      idCode.style.fontSize = "0.85em";
      idCode.style.backgroundColor = "var(--background-secondary)";
      idCode.style.padding = "2px 6px";
      idCode.style.borderRadius = "3px";
      const genderText = speaker.gender === "male" ? "\u7537" : speaker.gender === "female" ? "\u5973" : "\u672A\u77E5";
      row.createEl("td", { text: genderText });
      const audioCell = row.createEl("td");
      if (speaker.audioPreviewUrl) {
        const audioLink = audioCell.createEl("a", {
          text: "\u{1F3A7} \u8BD5\u542C",
          href: speaker.audioPreviewUrl,
          cls: "listenhub-audio-link"
        });
        audioLink.setAttr("target", "_blank");
      } else {
        audioCell.createEl("span", { text: "-", cls: "listenhub-no-audio" });
      }
      const actionCell = row.createEl("td");
      const useBtn1 = actionCell.createEl("button", { text: "\u7528\u4F5C\u97F3\u82721", cls: "listenhub-use-btn" });
      useBtn1.addEventListener("click", async () => {
        this.plugin.settings.speaker1 = speaker.id;
        await this.plugin.saveSettings();
        new import_obsidian.Notice(`\u2705 \u5DF2\u5C06 "${speaker.name}" \u8BBE\u4E3A\u97F3\u82721`);
        this.display();
      });
      const useBtn2 = actionCell.createEl("button", { text: "\u7528\u4F5C\u97F3\u82722", cls: "listenhub-use-btn" });
      useBtn2.style.marginLeft = "4px";
      useBtn2.addEventListener("click", async () => {
        this.plugin.settings.speaker2 = speaker.id;
        await this.plugin.saveSettings();
        new import_obsidian.Notice(`\u2705 \u5DF2\u5C06 "${speaker.name}" \u8BBE\u4E3A\u97F3\u82722`);
        this.display();
      });
    }
  }
};
